apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocodit-agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocodit-agent-frontend
  template:
    metadata:
      labels:
        app: autocodit-agent-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontendPort }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
            - name: NEXT_PUBLIC_WS_URL
              value: {{ .Values.frontend.env.NEXT_PUBLIC_WS_URL | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontendPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontendPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
