apiVersion: v1
kind: Service
metadata:
  name: autocodit-agent-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: autocodit-agent-frontend
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
