-- AutoCodit Agent Database Schema (Part 2: repositories, tasks, sessions)

-- Repositories table
CREATE TABLE IF NOT EXISTS repositories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    github_id INTEGER UNIQUE NOT NULL,
    full_name VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    default_branch VARCHAR(255) DEFAULT 'main',
    language VARCHAR(100),
    topics JSONB DEFAULT '[]',
    is_private BOOLEAN DEFAULT FALSE,
    is_fork BOOLEAN DEFAULT FALSE,
    is_archived BOOLEAN DEFAULT FALSE,
    installation_id UUID REFERENCES installations(id),
    agent_enabled BOOLEAN DEFAULT TRUE,
    default_agent_config_id UUID REFERENCES agentconfigs(id),
    auto_merge_enabled BOOLEAN DEFAULT FALSE,
    allowed_file_patterns JSONB DEFAULT '[]',
    ignored_file_patterns JSONB DEFAULT '[]',
    webhook_events JSONB DEFAULT '[]',
    webhook_secret VARCHAR(255),
    total_tasks INTEGER DEFAULT 0,
    successful_tasks INTEGER DEFAULT 0,
    failed_tasks INTEGER DEFAULT 0,
    structure_analysis JSONB DEFAULT '{}',
    dependency_analysis JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    priority VARCHAR(50) DEFAULT 'normal',
    repository_id UUID REFERENCES repositories(id),
    branch_name VARCHAR(255),
    base_branch VARCHAR(255) DEFAULT 'main',
    github_event_type VARCHAR(100),
    github_event_data JSONB DEFAULT '{}',
    issue_number INTEGER,
    pull_request_number INTEGER,
    user_id UUID REFERENCES users(id),
    agent_config_id UUID REFERENCES agentconfigs(id),
    timeout_minutes INTEGER DEFAULT 60,
    max_iterations INTEGER DEFAULT 20,
    auto_merge BOOLEAN DEFAULT FALSE,
    result_summary TEXT,
    files_changed JSONB DEFAULT '[]',
    commits_created JSONB DEFAULT '[]',
    tokens_used INTEGER DEFAULT 0,
    execution_time_seconds INTEGER,
    error_message TEXT,
    error_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES tasks(id),
    status VARCHAR(50) DEFAULT 'initializing',
    runner_id VARCHAR(255),
    container_id VARCHAR(255),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    plan JSONB DEFAULT '{}',
    current_step INTEGER DEFAULT 0,
    total_steps INTEGER DEFAULT 0,
    workspace_path VARCHAR(500),
    context_data JSONB DEFAULT '{}',
    ai_model_used VARCHAR(100),
    prompt_tokens INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    tools_used JSONB DEFAULT '[]',
    tool_results JSONB DEFAULT '{}',
    memory_usage_mb INTEGER,
    cpu_usage_percent NUMERIC,
    output_files JSONB DEFAULT '[]',
    generated_commits JSONB DEFAULT '[]',
    test_results JSONB DEFAULT '{}',
    error_details TEXT,
    retry_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
